### ISSUE TITLE
Question on proramming Atmega328

### ISSUE THREAD

**Issue by mamejay** [planeturban/15khzvgatester#5] opened 2019-09-04 03:34 UTC
This is probably  a silly question but how can I program a Atmega328 chip on its own using Ardunio IDE?  I normally use avrdude, a UNO and a HEX file.
What board do i set the Arduino IDE to?

**Comment by planeturban** [comment] 2019-09-04 13:42
You could probably use arduino pro mini, but you'll have to re-set the fuses to no BODLevel. I'm using the following fuses:
E: 0xFF
H: 0xDA
L: 0xFF

As for hex-file, use "Compile" and then "Export compiled binary" under Sketch-menu and then use avrdude. I guess.

Duplicate of #2

**Closed as completed by planeturban** 2019-09-04 13:42 UTC
